### ISSUE TITLE
Star icon missing in nautilus

### ISSUE THREAD

**Issue by lex-andr** [tully-t/Sours#1]
The icon for starred items seems to be missing.
This happens in nautilus. As an example I starred the Downloads folder an looks like this:
![2024-10-16_11-18](https://github.com/user-attachments/assets/2e00400a-0efa-48cf-9f4a-9b7f9cb73322)

The same happens in the item "Properties" menu.
Would be nice to solve it!

**Comment by tully-t** [comment]
Thank you for letting me know! I'm a KDE user so this is super helpful.  I think I fixed it by adding a starred.svg to the Actions folder, lmk if I am wrong.

**Comment by lex-andr** [comment]
Yes, that fixed it! Thanks!
